BOT_API_TOKEN = ""

LINK_TO_WEBSITE = "https://link2website.example"
LINK_TO_SUBSCRIBE = "https://link2sub.example"

SUPPORT_USERNAME = "S7459N"
LINK_TO_SUPPORT = f"https://t.me/{SUPPORT_USERNAME}"

WALLET_EXPIRE_SECONDS = 10

SERVER_HOST_IP = '127.0.0.1'
SERVER_HOST_PORT = 8887

SUB_COST = 50

